' Copyright (c) 2020 Thomas Hugo Williams

Option Explicit On
Option Default Integer

Const IN_FILE$ = "resources/allKeywords.tkn"
Const OUT_FILE$ = "tokens.inc"

Dim buf$
Dim count
Dim pos_ = 0
Dim tokens$(599)

Cls
count = read_file(IN_FILE$)
Print "Read " + Str$(count) + " tokens"
Sort tokens$()
count = write_file(OUT_FILE$)
Print "Wrote " + Str$(count) + " unique tokens"
End

Function read_file(f$)
  Local ch, t$

  Open f$ For Input As #1

  Do
    ch = read_char()
    If ch = -1 Then Exit Do
  Loop Until ch = -1 or ch = Asc("@")

  If ch = -1 Then Error "No @ symbol"

  pos_ = pos_ - 1
  Do
    ch = read_char()
    If ch = -1 Then Exit Do
    If ch <= &h20 Then
      If Len(t$) > 0 Then
        tokens$(count) = t$
        count = count + 1
      EndIf
      t$ = ""
    Else
      t$ = t$ + Chr$(ch)
    EndIf
  Loop

  Close #1

  read_file = count
End Function

Function read_char()
  pos_ = pos_ + 1
  If pos_ > Len(buf$) Then fill_buf()
  If Len(buf$) = 0 Then
    read_char = -1
  Else
    read_char = Peek(Var buf$, pos_)
  EndIf
End Function

Sub fill_buf()
  buf$ = Input$(255, #1)
  pos_ = 1
End Sub

Function write_file(f$)
  Local count, i, skip, t$

  Open f$ For Output As #1

  Print #1, "' File autogenerated on " + Date$ + " " + Time$
  Print #1

  count = 0
  For i = 0 To 599
    t$ = tokens$(i)
    skip = t$ = ""
    If i > 0 And Not skip Then skip = t$ = tokens$(i - 1)
    If Not skip Then
      If Left$(t$, 1) = "#" Then
        t$ = "HASH_" + Right$(t$, Len(t$) - 1)
      ElseIf Left$(t$, 1) = "@" Then
        t$ = "AT" + Right$(t$, Len(t$) - 1)
      EndIf

      If Right$(t$, 2) = "$(" Then
        t$ = Left$(t$, Len(t$) - 2) + "_S_FN"
      ElseIf Right$(t$, 1) = "(" Then
        t$ = Left$(t$, Len(t$) - 1) + "_FN"
      ElseIf Right$(t$, 1) = "$" Then
        t$ = Left$(t$, Len(t$) - 1) + "_S"
      EndIf

      Print #1, "Dim T_" + UCase$(t$) + " = " + Str$(count)
      count = count + 1
    EndIf
  Next i

  Print #1
  Print #1, "Dim NUM_TOKENS = " + Str$(count)
  Print #1, "Dim TOKENS$(NUM_TOKENS - 1) Length 15"
  Print #1

  count = 0
  For i = 0 To 599
    t$ = tokens$(i)
    skip = t$ = ""
    If i > 0 And Not skip Then skip = t$ = tokens$(i - 1)
    If Not skip Then
      Print #1, "TOKENS$(" + Str$(count) + ") = " + Chr$(34) + t$ + Chr$(34)
      count = count + 1
    EndIf
  Next i

  Close #1

  write_file = count
End Function

